name: cejs
on:
  workflow_dispatch:
    inputs:
      ids:
        required: true
      scheme:
        type: choice
        required: true
        options:
          - u17
        default: u17
      storage:
        type: choice
        required: true
        options:
          - cloud189
          - releases
        default: cloud189
defaults:
  run:
    shell: bash
env:
  resIds: ${{ inputs.ids }}
  resScheme: ${{ inputs.scheme }}
  resStor: ${{ inputs.storage }}
  cejsVer: 4.5.4
jobs:
  in-one-go:
    runs-on: ubuntu-latest
    steps:
      - name: apt()
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -qq libarchive-tools pixz </dev/null >/dev/null
      - name: cache.npm(cejscrawler)
        uses: actions/cache@v3
        with:
          path: cejscrawler
          key: node_modules-cejscrawler-v${{ env.cejsVer }}-ubuntu-latest
      - name: npm(cejscrawler)
        run: |
          if ! [[ -d cejscrawler ]]; then
            git clone -qb flos --depth 1 --single-branch https://github.com/flosnvjx/work_crawler.git/ cejscrawler
            env -C cejscrawler -- npm install --silent cejs@"${cejsVer}"
          fi
      - name: cejscrawler.${{ inputs.scheme }}(${{ inputs.ids }})
        run: |
          printf '%s' "$resIds" | sed -zsEe 's%[,; ]+%\n%g' -e '/^$/d' -e '$a\\' > "$resScheme".txt
          node cejscrawler/comic.cmn-Hans-CN/u17.js l="$resScheme".txt
          ls -R ../dl
          ls -R dl
          ls -R u17
