name: cejs
on:
  workflow_dispatch:
    inputs:
      ids:
        required: true
      scheme:
        type: choice
        required: true
        options:
          - u17
        default: u17
      storage:
        type: choice
        required: true
        options:
          - cloud189
          - releases
        default: cloud189
defaults:
  run:
    shell: bash
env:
  resIds: ${{ inputs.ids }}
  resScheme: ${{ inputs.scheme }}
  resStor: ${{ inputs.storage }}
  cejsVer: 4.5.4
jobs:
  in-one-go:
    runs-on: ubuntu-latest
    steps:
      - name: apt()
        run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -qq libarchive-tools pixz </dev/null >/dev/null
      - name: cache.npm(cejscrawler)
        uses: actions/cache@v3
        with:
          path: cejscrawler
          key: node_modules-cejscrawler-v${{ env.cejsVer }}-ubuntu-latest
      - name: npm(cejscrawler)
        run: |
          if ! [[ -d cejscrawler ]]; then
            git clone -qb flos --depth 1 --single-branch https://github.com/flosnvjx/work_crawler.git/ cejscrawler
            env -C cejscrawler -- npm install --silent cejs@"${cejsVer}"
          fi
      - name: cejscrawler.${{ inputs.scheme }}(${{ inputs.ids }})
        run: |
          mkdir dl/"$resScheme"
          printf '%s' "$resIds" | sed -sEe 's%[,; ]+%\n%g' | grep -e '^[0-9]+$' | \
          xargs -rI'{}' -P3 | bash -c "
          if NODE_TLS_REJECT_UNAUTHORIZED=0 node cejscrawler/comic.cmn-Hans-CN/u17.js {} archive_images=false preserve_work_page min_length=1024 max_error_retry=1 one_by_one chapter_time_interval=3s; then
            echo {} >> dl/$resScheme/ok.lst
            sleep $(shuf -i 0-3)
          else
            echo {} >> dl/$resScheme/err.lst
            sleep $(shuf -i 0-3)
          fi
          "
          ls -lR dl
          find dl -name '*.json' | xargs -rL1 jq -r .
