on:
  workflow_dispatch:
    inputs:
      implementation:
        type: choice
        options:
          - cejs
        required: true
        default: 'cejs'
      resid:
        required: true
      resannot:
      storage:
        required: true
        type: choice
        default: 'release-asset'
        options:
          - release-asset
name: 'update()'
run-name: 'update.'${{ inputs.implementation }}'('${{ inputs.resid }}'#"'${{ inputs.resannot }}'")'
jobs:
  in-one-go:
    runs-on: ubuntu-latest
    steps:
      - run: echo a
