on:
  workflow_call:
    inputs:
      implementation:
        type: string
        default: 'cejs'
      resid:
        type: string
        required: true
      resannot:
        type: string
      storage:
        type: string
        default: 'release-asset'
  workflow_dispatch:
    inputs:
      implementation:
        type: choice
        options:
          - cejs
        default: 'cejs'
        required: true
      resid:
        type: string
        required: true
      resannot:
        type: string
      storage:
        type: choice
        default: 'release-asset'
        options:
          - release-asset
        required: true
name: update()
## *name: ensure that there is no 'string' in expression
run-name: update.${{ inputs.implementation }}(${{ inputs.resid }}#${{ inputs.resannot }})
jobs:
  main:
    steps:
      - run: echo o
