on:
  workflow_call:
    inputs:
      implementation:
        type: choice
        options:
          - cejs
        default: 'cejs'
      resid:
        required: true
      resannot:
      storage:
        type: choice
        default: 'release-asset'
        options:
          - release-asset
  workflow_dispatch:
    inputs:
      implementation:
        type: choice
        options:
          - cejs
        default: 'cejs'
      resid:
        required: true
      resannot:
      storage:
        type: choice
        default: 'release-asset'
        options:
          - release-asset
name: update()
## *name: ensure that there is no 'string' in expression
run-name: update.${{ inputs.implementation }}(${{ inputs.resid }}#${{ inputs.resannot }})
