on:
  workflow_dispatch:
  schedule:
    - cron: '24 8,13,18 * * 1,3,5'
    - cron: '03 6,11,16 * * 2,4,6'
name: update-trigger()
defaults:
  run:
    shell: bash
permissions:
  actions: write
  checks: none
  contents: write
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update&&sudo apt install zsh
      - run: scripts/update-trigger trigger
        env:
          GH_TOKEN: ${{ github.token }}
